### ISSUE TITLE
Charts are getting cutoff at the right end

### ISSUE THREAD

**Issue by accforgithubtest** [lovasoa/SQLpage#172] opened 2024-01-04 05:11 UTC
The bars on the right most corner are cutoff (see next image for the correct number of bars) - Dec 23 data is cut off at the right side of the chart - 
![image](https://github.com/lovasoa/SQLpage/assets/128544172/da674a5e-6cd6-43f0-a1ce-f943a9a76c1a)

After manually adding an empty row for an extra month, to create extra space on the right side -
![image](https://github.com/lovasoa/SQLpage/assets/128544172/6e9bfd82-2609-481e-b126-0f096f490c02)

If it helps - Viewing this on a standard 27" 1140p monitor, maximized window as well.

**Comment by lovasoa** [comment] 2024-01-04 09:19
Thanks for reporting this !
Can you please provide a small sql file that reproduces this ?

**Comment by lovasoa** [comment] 2024-01-04 09:44
Ok, I can reproduce it with the following SQLite snippet:

```sql
select 
    'chart'    as component,
    'bar'      as type,
    TRUE       as toolbar,
    TRUE       as time;

with recursive integers(i) as (
    select 1 as i
    union all
    select i + 1
    from integers
    where i < 100
)
select 
    'S' || (i%10) as series,
    format('%d-01-01', 2010 + (i/10))     as x,
    (random() % 10)   as value
from integers;
```

![image](https://github.com/lovasoa/SQLpage/assets/552629/c8bcd06d-f29b-4fab-8828-73f22b6964e9)

**Comment by lovasoa** [comment] 2024-01-04 14:14
I reported the issue upstream, since the bug seems to be in apexcharts, not in SQLPage itself: https://github.com/apexcharts/apexcharts.js/issues/4178

**Comment by DSMejantel** [comment] 2024-01-08 20:45
I have similar problems with long series.
I want series as stacked values for each classes.
It's ok for 1st et 2nd and after it's horrible. Some classes are a lot of times on x axys.
For the 3rd, instead of the "34" we have the "41" !
![image](https://github.com/lovasoa/SQLpage/assets/149260856/2fc50817-8914-432a-aae1-32b7af59cc95)

There is the code : 
`-- Différents Dispositifs en place par Classe
select 
    'chart'               as component,
    'Différents dispositifs par classe' as title,
    'bar'             as type,
        500 as height,
    TRUE as labels,
    TRUE as stacked,
    'Classes' as xtitle,
    'Nombre de dispositifs' as ytitle;
select 
    Nom_dispositif as series,
    classe as x,
    coalesce(Nombre,0) as value
    FROM stats01 WHERE etab=$id ORDER BY classe;

`This is the beginning of the debug with "34" as 3rd position...
`Debug output

{"component":"debug","title":"Différents dispositifs par classe","type":"bar","height":500,"labels":true,"stacked":true,"xtitle":"Classes","ytitle":"Nombre de dispositifs"}

{"series":"SEGPA","x":"31","value":5}

{"series":"UEE","x":"31","value":2}

{"series":"ULIS","x":"31","value":2}

{"series":"Mat. Pédagogique","x":"33","value":2}

{"series":"PAI","x":"33","value":1}

{"series":"PIAL","x":"33","value":2}

{"series":"PPRE","x":"33","value":2}

{"series":"SEGPA","x":"33","value":1}

{"series":"ULIS","x":"33","value":2}

{"series":"FLS","x":"34","value":3}

{"series":"Mat. Pédagogique","x":"34","value":1}`

**Comment by lovasoa** [comment] 2024-01-10 19:55
Is this a different issue than https://github.com/lovasoa/SQLpage/issues/172 ? If it's the same problem, I don't think we need to track it twice. It has already been reported to the graph library upstream: https://github.com/apexcharts/apexcharts.js/issues/4178

**Comment by lovasoa** [comment] 2024-02-12 09:17
ApexCharts just [merged a fix for this issue](https://github.com/apexcharts/apexcharts.js/pull/4228). It will be included in SQLPage's next version :confetti_ball:

**Closed** 2024-07-11 11:46 UTC
Labels: bug
