### ISSUE TITLE
SQLPage - displaying the current version

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#390] opened 2024-06-09 20:57 UTC
Hi, 
When we run the SQLPage binary, it doesn't show the version. Is there a way to display it?

Thanks

**Comment by lovasoa** [comment] 2024-06-09 21:21
Hi !
  I think this is a duplicate of : https://github.com/lovasoa/SQLpage/discussions/280

  But since it is the second time it comes up, I'll add it to the logs that are shown on startup.

**Closed** 2024-06-09 21:22 UTC
Labels: enhancement
